# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-28 09:08
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0010_auto_20160615_1633'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categorymenu',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
