# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-18 11:42
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('claim', '0012_auto_20170324_1143'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='categorymenu',
            managers=[
                ('_default_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
