# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 11:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0015_event_opsos_name_opsos_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='logging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.SlugField(max_length=30, verbose_name='Приложение')),
                ('old_value', models.CharField(blank=True, max_length=100, null=True, verbose_name='Старое значение')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время записи')),
                ('event_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Event', verbose_name='Событие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие ',
                'verbose_name_plural': 'Журнал событий ',
            },
        ),
    ]
