# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(blank=True, help_text='Допустим: search', max_length=10, verbose_name='Класс иконки bootstrap'),
        ),
    ]
