# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0014_transmitter_serial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, unique=True, verbose_name='Наименование события')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Алиас')),
            ],
            options={
                'verbose_name': 'Событие ',
                'verbose_name_plural': 'События ',
            },
        ),
        migrations.CreateModel(
            name='OpSoS_name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Сотовый оператор',
                'verbose_name_plural': 'Список сотовых операторов ',
            },
        ),
        migrations.CreateModel(
            name='OpSoS_rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('Descript', models.TextField(verbose_name='Описание тарифа')),
                ('OpSoSName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.OpSoS_name', verbose_name='Сотовый оператор')),
            ],
            options={
                'verbose_name': 'Тариф ',
            },
        ),
    ]
