# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reference_books', '0015_event_opsos_name_opsos_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsos_rate',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Абонентская плата'),
        ),
    ]
