# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-13 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_trouble_shooting_routes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance_request',
            name='TypeSecurity',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Объём работ'),
        ),
    ]
