# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-03-23 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference_books', '0015_event_opsos_name_opsos_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpSoS_card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_SIM', models.IntegerField(verbose_name='Номер сим-карты')),
                ('ICC_SIM', models.CharField(max_length=20, verbose_name='Ид.код сим-карты')),
                ('Contract', models.CharField(max_length=100, verbose_name='Договор')),
                ('Contract_date', models.DateField(verbose_name='Дата')),
                ('PersonalAccount', models.IntegerField(verbose_name='Лицевой счёт')),
                ('Use_numberobject', models.CharField(blank=True, max_length=30, verbose_name='Номер объекта')),
                ('Use_addressobject', models.CharField(blank=True, max_length=300, verbose_name='Адрес объекта')),
                ('Use_user', models.CharField(blank=True, max_length=100, verbose_name='Фамилия Имя Отчество')),
                ('Notation', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('Status', models.BooleanField(default=True, verbose_name='SIM-карта активна')),
                ('DateTime_add', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время добавления')),
                ('DateTime_update', models.DateTimeField(auto_now=True, verbose_name='Дата и время обновления')),
                ('Create_user', models.IntegerField(verbose_name='ID пользователя создавшего запись')),
                ('Update_user', models.IntegerField(blank=True, null=True, verbose_name='ID пользователя изменившего запись')),
                ('OpSoSRate', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='reference_books.OpSoS_rate', verbose_name='Тариф')),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reference_books.Company', verbose_name='Контрагент оператора')),
            ],
            options={
                'verbose_name': 'СИМ-карта ',
                'verbose_name_plural': 'Список сим-карт ',
            },
        ),
        migrations.CreateModel(
            name='UseTypeSIM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='алиас')),
            ],
            options={
                'verbose_name': 'Тип ',
                'verbose_name_plural': 'Типы применения SIM-карт ',
            },
        ),
        migrations.AddField(
            model_name='opsos_card',
            name='Use_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sim.UseTypeSIM', verbose_name='Тип применения'),
        ),
    ]
