# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2018-01-19 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sim', '0003_auto_20180119_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsos_card',
            name='ICC_SIM',
            field=models.CharField(max_length=22, verbose_name='Ид.код сим-карты'),
        ),
        migrations.AlterField(
            model_name='opsos_card',
            name='Number_SIM',
            field=models.CharField(max_length=20, verbose_name='Номер сим-карты'),
        ),
    ]
